#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter()
{
	// 디폴트 파일 이름만 바꾼다.
	_fileName = "NoNae.html";

	// 디폴트 폰트를 지정한다.
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "black";
}
HTMLWriter::HTMLWriter(const string& fileName, const string& content)
	: DocWriter(fileName, content)
{
	// 디폴트 폰트를 지정한다.
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "black";
}
HTMLWriter::~HTMLWriter()
{

}

// 파일에 텍스트를 저장시킨다.
void HTMLWriter::Write()
{
	// 파일을 연다.
	ofstream of(_fileName.c_str());

	// HTML 헤더 부분을 지정한다.
	of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter</TITLE></HEAD><BODY>";
	of << "<H1>Content</H1>";

	// 폰트 태그를 시작한다.
	of << "<Font name = " << _fontName << "' size = '" << _fontSize << "' color = '" << _fontColor << "'>";

	// 텍스트를 저장한다.
	of << _content;

	// 폰트 태그를 닫는다.
	of << "</FONT>";

	// HTML을 마무리한다.
	of << "</BODY></HTML>";
}

// 폰트를 지정한다.
void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor)
{
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}